name: Gradle CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Build with Gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build --no-daemon --stacktrace
